"use client";

import { useState } from "react";
import { CheckCircle2, ChevronLeft, ChevronRight, RotateCcw, Sparkles } from "lucide-react";
import { submitPractice } from "@/app/actions/exams";
import type { ExamQuestion } from "@/lib/supabase/types";

export default function PracticeRunner({ paper }: { paper: { id: string; subject: string; year: number; examination_name: string; paper_number: string; instructions: string; questions: ExamQuestion[] } }) {
  const [answers, setAnswers] = useState<Record<string, string>>({});
  const [index, setIndex] = useState(0);
  const [result, setResult] = useState<{ marksObtained: number; totalMarks: number; percentage: number; areasToImprove: string[]; markedAnswers: Array<{ questionId: string; marksAwarded: number; status: string; feedback: string; explanation: string }> } | null>(null);
  const [busy, setBusy] = useState(false);
  const question = paper.questions[index];
  const answered = Object.values(answers).filter(Boolean).length;
  async function submit() { if (answered < paper.questions.length && !window.confirm("You still have unanswered questions. Submit practice anyway?")) return; setBusy(true); const response = await submitPractice(paper.id, paper.questions.map((item) => ({ questionId: item.id, answer: answers[item.id] || "" }))); setBusy(false); if (response.result) setResult(response.result); }
  if (result) return <div className="learn-card p-6 sm:p-8"><div className="flex items-center gap-2 text-emerald-700"><CheckCircle2 className="w-5 h-5" /><h2 className="text-xl font-black">Practice marked</h2></div><p className="text-3xl font-black text-slate-900 mt-4">{result.marksObtained}/{result.totalMarks} <span className="text-base text-slate-500">({result.percentage}%)</span></p>{result.areasToImprove.length > 0 && <div className="mt-5 p-4 rounded-2xl bg-amber-50 border border-amber-200"><p className="text-sm font-bold text-amber-900">Practice your weak areas</p><div className="flex flex-wrap gap-2 mt-3">{result.areasToImprove.map((area) => <span key={area} className="px-2.5 py-1 rounded-full bg-white text-xs font-bold text-amber-800">{area}</span>)}</div></div>}<div className="space-y-3 mt-6">{paper.questions.map((item) => { const mark = result.markedAnswers.find((answer) => answer.questionId === item.id); return <div key={item.id} className="p-4 rounded-xl bg-slate-50"><div className="flex justify-between gap-3"><p className="text-sm font-bold text-slate-800">Question {item.question_number}</p><span className="text-xs font-bold text-indigo-700">{mark?.marksAwarded || 0}/{item.marks}</span></div><p className="text-xs text-slate-600 mt-2">{mark?.feedback}</p>{mark?.explanation && <p className="text-xs text-slate-500 mt-1">{mark.explanation}</p>}</div>; })}</div><button type="button" onClick={() => { setAnswers({}); setResult(null); setIndex(0); }} className="inline-flex items-center gap-2 mt-6 px-4 py-2.5 rounded-xl bg-indigo-600 text-white text-xs font-bold"><RotateCcw className="w-4 h-4" />Retry paper</button></div>;
  return <div className="learn-card p-5 sm:p-7"><div className="flex items-start justify-between gap-4 mb-6"><div><p className="text-xs font-bold uppercase tracking-wider text-indigo-600">Question {index + 1} of {paper.questions.length}</p><h2 className="text-lg font-bold text-slate-900 mt-2">{question.question_text}</h2></div><span className="px-2.5 py-1 rounded-lg bg-slate-100 text-xs font-bold text-slate-600">{question.marks} marks</span></div>{question.question_type === "multiple_choice" || question.question_type === "true_false" ? <div className="space-y-3">{question.options.map((option) => <label key={option} className={`flex items-center gap-3 p-3 rounded-xl border cursor-pointer ${answers[question.id] === option ? "border-indigo-400 bg-indigo-50" : "border-slate-200"}`}><input type="radio" name={question.id} checked={answers[question.id] === option} onChange={() => setAnswers((previous) => ({ ...previous, [question.id]: option }))} className="accent-indigo-600" />{option}</label>)}</div> : <textarea value={answers[question.id] || ""} onChange={(event) => setAnswers((previous) => ({ ...previous, [question.id]: event.target.value }))} rows={8} className="w-full rounded-xl border border-slate-200 p-3 text-sm" placeholder="Write your answer..." />}{index === paper.questions.length - 1 && <button type="button" onClick={() => void submit()} disabled={busy} className="mt-6 inline-flex items-center gap-2 px-4 py-2.5 rounded-xl bg-emerald-600 text-white text-xs font-bold disabled:opacity-60"><Sparkles className="w-4 h-4" />{busy ? "Marking..." : "Submit Practice"}</button>}<div className="flex items-center justify-between gap-3 mt-6 pt-4 border-t border-slate-100"><button type="button" disabled={index === 0} onClick={() => setIndex((value) => value - 1)} className="inline-flex items-center gap-1 text-xs font-bold text-slate-600 disabled:opacity-40"><ChevronLeft className="w-4 h-4" />Previous</button><span className="text-xs text-slate-400">{answered} answered</span>{index < paper.questions.length - 1 ? <button type="button" onClick={() => setIndex((value) => value + 1)} className="inline-flex items-center gap-1 text-xs font-bold text-indigo-600">Next<ChevronRight className="w-4 h-4" /></button> : <span />}</div></div>;
}
