import Link from "next/link";
import { ArrowRight, CalendarClock, ClipboardCheck, History, Sparkles } from "lucide-react";
import { getPublishedExams } from "@/app/actions/exams";

export default async function LearnerExamsPage() {
  const exams = await getPublishedExams();
  return <div className="max-w-7xl mx-auto space-y-7 pb-12">
    <header className="flex flex-col sm:flex-row sm:items-end justify-between gap-4"><div><div className="flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-indigo-600"><ClipboardCheck className="w-4 h-4" />Learner Portal</div><h1 className="text-2xl sm:text-3xl font-black text-slate-900 mt-2">Examinations</h1><p className="text-sm text-slate-500 mt-1">Take secure, timed assessments and turn every result into a revision plan.</p></div><div className="flex gap-2"><Link href="/learner/exams/history" className="inline-flex items-center gap-2 px-3.5 py-2.5 rounded-xl bg-white border border-slate-200 text-xs font-bold text-slate-700"><History className="w-4 h-4" />Exam history</Link><Link href="/learner/past-papers" className="inline-flex items-center gap-2 px-3.5 py-2.5 rounded-xl bg-indigo-600 text-white text-xs font-bold"><Sparkles className="w-4 h-4" />Past papers</Link></div></header>
    <div className="grid sm:grid-cols-3 gap-4"><Stat label="Available assessments" value={String(exams.filter((exam) => exam.status === "available").length)} /><Stat label="Published exams" value={String(exams.length)} /><Stat label="Server-timed" value="100%" /></div>
    <section className="grid md:grid-cols-2 xl:grid-cols-3 gap-5">{exams.map((exam) => { const upcoming = exam.status === "upcoming"; const closed = exam.status === "completed"; return <article key={exam.id} className="learn-card learn-card-hover p-5 flex flex-col"><div className="flex items-start justify-between gap-3"><span className="px-2.5 py-1 rounded-full bg-indigo-50 text-indigo-700 text-[10px] font-black uppercase tracking-wide">{exam.subject}</span><span className={`px-2.5 py-1 rounded-full text-[10px] font-bold ${closed ? "bg-slate-100 text-slate-500" : upcoming ? "bg-amber-50 text-amber-700" : "bg-emerald-50 text-emerald-700"}`}>{closed ? "Completed" : upcoming ? "Upcoming" : "Available"}</span></div><h2 className="text-lg font-bold text-slate-900 mt-4">{exam.title}</h2><p className="text-sm text-slate-500 mt-2 line-clamp-2">{exam.description}</p><div className="grid grid-cols-2 gap-2 mt-5 text-xs"><Info label="Questions" value="Open details" /><Info label="Marks" value={String(exam.total_marks)} /><Info label="Duration" value={`${exam.duration_minutes} min`} /><Info label="Closes" value={new Date(exam.closes_at).toLocaleDateString()} /></div><div className="mt-5 pt-4 border-t border-slate-100 flex items-center justify-between gap-3"><span className="flex items-center gap-1.5 text-[11px] text-slate-500"><CalendarClock className="w-3.5 h-3.5" />Starts {new Date(exam.starts_at).toLocaleString([], { dateStyle: "medium", timeStyle: "short" })}</span><Link href={`/learner/exams/${exam.id}`} className={`inline-flex items-center gap-1.5 px-3 py-2 rounded-xl text-xs font-bold ${closed ? "bg-slate-100 text-slate-600" : "bg-indigo-600 text-white"}`}>{closed ? "View" : "Start Exam"}<ArrowRight className="w-3.5 h-3.5" /></Link></div></article>; })}</section>
    {exams.length === 0 && <div className="learn-card p-10 text-center text-sm text-slate-500">No published examinations are available yet.</div>}
  </div>;
}
function Stat({ label, value }: { label: string; value: string }) { return <div className="learn-card p-4"><p className="text-xs text-slate-500">{label}</p><p className="text-2xl font-black text-slate-900 mt-1">{value}</p></div>; }
function Info({ label, value }: { label: string; value: string }) { return <div className="rounded-xl bg-slate-50 p-2.5"><p className="text-[10px] uppercase text-slate-400 font-bold">{label}</p><p className="text-xs font-bold text-slate-700 mt-1 truncate">{value}</p></div>; }
